version: '3'

services:
  loops_as_a_service_dev:
    container_name: loops_as_a_service_dev
    image: cloudblueconnect/connect-extension-runner:24.4
    command: cextrun -d
    volumes: 
      - .:/extension
    env_file:
      - .loops_as_a_service_dev.env

  loops_as_a_service_bash:
    container_name: loops_as_a_service_bash
    image: cloudblueconnect/connect-extension-runner:24.5
    working_dir: /extension
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    env_file:
      - .loops_as_a_service_dev.env

  loops_as_a_service_test:
    container_name: loops_as_a_service_test
    image: cloudblueconnect/connect-extension-runner:24.5
    working_dir: /extension
    command: /bin/bash -c "poetry install && pytest --verbose --cov=loops_connect_ext --cov-report=html --cov-report=term-missing:skip-covered"
    volumes:
      - .:/extension
    env_file:
      - .loops_as_a_service_dev.env
